name: ESP32 Build

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          path: .
          target: esp32
          command: idf.py fullclean build

      - name: Copy .bin files to firmware folder
        run: |
          mkdir -p firmware
          cp -v build/*.bin firmware/

      - name: Upload firmware as artifact
        uses: actions/upload-artifact@v4
        with:
          name: esp32-firmware
          path: firmware/
