name: ESP32 Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up ESP-IDF and Build Project
        uses: espressif/esp-idf-ci-action@v1
        with:
          path: esp_project/blink 
          target: esp32        # Set your chip (esp32, esp32c3, esp32s3, etc.)
          command: idf.py build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: esp32-build
          path: esp_project/blink/build
