name: Run Shell Commands

on: [push]

jobs:
  run-terminal:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Shell Commands
        run: |
          echo "This is running in GitHub Actions"
          ls -la
          pwd
          echo "Done."
