name: ESP32 Build

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          path: .
          target: esp32
          command: idf.py fullclean build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: esp32-build
          path: ./build

      - name: Create firmware folder and copy bin files
        run: |
            mkdir -p firmware
            cp build/*.bin firmware/


      - name: Move build artifacts to repo build folder
        run: |
          mkdir -p build
          cp -v ./firmware/*.bin ./build/

      - name: Commit and push build artifacts
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add build/*.bin
          git commit -m "Add compiled firmware binaries"
          git push origin main



